# Generated by Django 5.2.6 on 2025-12-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('departement', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('nomProjet', models.CharField(max_length=200)),
                ('typeAccord', models.CharField(max_length=100)),
                ('choix', models.BooleanField()),
                ('etablissementPartenaire', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('durée', models.CharField(max_length=100)),
                ('objectif', models.TextField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('dossier_pdf', models.FileField(blank=True, null=True, upload_to='dossiers/')),
            ],
        ),
    ]
