# Generated by Django 5.2.6 on 2025-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='etat',
            field=models.CharField(choices=[('ferme', 'Fermé'), ('en attente de DRI', 'En attente de DRI'), ('en attente de DEVE', 'En attente de DEVE'), ('en attente de CEVE', 'En attente de CAEVE'), ('en attente de CEVU', 'En attente de CEVU'), ('en attente de CA', 'En attente de CA'), ('accepté', 'Accepté'), ('rejeté', 'Rejeté')], default='ferme', max_length=20),
        ),
    ]
